version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: java-maven-app
    container_name: java-maven-container
    environment:
      - JAVA_OPTS=-Xmx256m -Xms128m
    stdin_open: true
    tty: true